modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://example.com/heavy-storms/issues"

[[mods]]
modId="heavy_storms"
version="${file.jarVersion}"
displayName="Heavy Storms"
updateJSONURL=""
displayURL="https://example.com/heavy-storms"
credits=""
authors="nolyn"
description='''
Supercharge thunderstorms and channel lightning into Forge Energy.
'''

[[dependencies.heavy_storms]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.heavy_storms]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
