#Controls the intensity of thunder storms.
[lightning]
	#How many extra attempts to spawn lightning should be made each server tick while thundering.
	# Default: 3
	# Range: 0 ~ 100
	extraAttemptsPerTick = 3
	#Chance (0.0-1.0) that an extra lightning strike attempt actually spawns a bolt.
	# Default: 0.35
	# Range: 0.0 ~ 1.0
	extraStrikeChance = 0.35
	#Maximum horizontal distance (in blocks) from a nearby player where extra lightning may be spawned.
	# Default: 64
	# Range: 8 ~ 256
	extraStrikeRadius = 64

#Lightning capacitor settings.
[capacitor]
	#Total FE the Lightning Capacitor can store.
	# Default: 1000000
	# Range: > 1000
	capacity = 1000000
	#Maximum FE the capacitor can receive per operation from automation.
	# Default: 20000
	# Range: > 1
	maxReceive = 20000
	#Maximum FE the capacitor can output per operation to automation.
	# Default: 20000
	# Range: > 1
	maxExtract = 20000
	#How much FE a single lightning strike generates inside the capacitor.
	# Default: 500000
	# Range: > 1
	chargePerStrike = 500000
